language: python
sudo: required
dist: xenial

python:
  - "2.7"
  - "3.6"
  - "3.7"

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.0
    - python: "2.7"
      env: DJANGO_VERSION=2.1
    - python: "2.7"
      env: DJANGO_VERSION=2.2
    - python: "3.7"
      env: DJANGO_VERSION=1.11

install:
  - poetry install
  - pip install -U Django~=$DJANGO_VERSION

script:
  - poetry run flake8
  - poetry run runtests.py
