language: python
sudo: required
dist: xenial

python:
  - "2.7"
  - "3.6"
  - "3.7"

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.0
    - python: "2.7"
      env: DJANGO_VERSION=2.1
    - python: "2.7"
      env: DJANGO_VERSION=2.2
    - python: "2.7"
      env: DJANGO_VERSION=3.0

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -U flake8 flake8-quotes flake8-commas flake8-import-order mock
  - pip install coveralls

script:
  - flake8
  - coverage run --source=speedinfo runtests.py

after_success:
  - coveralls
